# Travis CI build file for iOSSampleKituraBuddy.

branches:
	only:
		- master
		- develop
		- /^issue.*$/

matrix:
	include:
		- os: linux
		  dist: trusty
		  sudo: required
		  env: COMPONENT=server
		- os: osx
		  osx_image: xcode0
		  sudo: required
	  	  env: COMPONENT=server
		- os: osx
		  osx_image: xcode9
		  env: COMPONENT=iOS

before install:
	- git clone https://github.com/IBM-Swift/Package-Builder.git
	- git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/Testing-Credentials.git

script:
	- if [[ "$COMPONENT" == "server" ]]; then cd KituraServer && "./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
	- if [[ "$COMPONENT" == "iOS" ]]; then cd $TRAVIS_BUILD_DIR/KituraiOS; xcodebuild -xcodeproj iOS\ Sample\ Kitura\ Buddy.xcodeproj/ -scheme iOS\ Sample\ Kitura\ Buddy -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO -quiet; fi
